config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#index"

  get :login, :to => "session#new"
  post :login, :to => "session#create"
  post :logout, :to => "session#destroy"

  resource :user, except: [:destroy] do
    resources :events, except: [:index, :show] do
      get :held, on: :collection
      get :detail, on: :member
    end
    get :activate, on: :member
  end

  resources :events, only: [:index, :show] do
    get :join, on: :member
    post :join, on: :member
    post :unjoin, on: :member
    get :joined, on: :collection
  end

  # resources :mailsender, only: [:index] do
  #   post :check, on: :collection
  #   post :send, on: :collection
  #   get :result, on: :collection
  # end

  get '/mailsender', to: "mailsender#create", as: 'mailsender_index'
  post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
  post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'

  namespace :admin do
    root :to => "pages#index"
    resources :users
    resources :events

    get '/mailsender', to: "mailsender#index", as: 'mailsender_index'
    get '/mailsender/create', to: "mailsender#create", as: 'mailsender_create'
    post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
    post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  markdown    :boolean          default(FALSE)
#  charge      :integer
#  location    :string
#  start_time  :date
#  join_limit  :date
#  owner_id    :integer
#  official    :boolean          default(FALSE)
#  deleted     :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :user_events, dependent: :destroy
  has_many :participated_user, through: :user_events, source: :user

  before_validation :convert_to_markdown
  
  scope :deleted_events, -> { where(deleted: true) }
  scope :available_events, -> { where(deleted: false) }
  scope :after_finishing, -> { where('? > start_time', Date.today) }
  scope :before_beginning, -> { where('? <= start_time', Date.today) }
  scope :acceptance_finished, -> { where('join_limit < ?', Date.today) }
  scope :during_acceptance, -> { where('join_limit >= ?', Date.today) }
  scope :member_events, -> { where(official: false) }
  scope :circle_events, -> { where(official: true) }

  validates :title, presence: true
  validates :description, presence: true
  validates :converted_description, presence: true
  validate :check_date
  validate :check_date_on_create, on: :create

  def check_date
    unless join_limit < start_time
      errors.add(:join_limit, "は#{:start_time}よりも前の日時にしてください")
      errors.add(:start_time, "は#{:join_limit}よりも後の日時にしてください")
    end
  end

  def check_date_on_create
    errors.add(:start_time, 'は今日以降の日時を指定してください') unless Date.today <= start_time
    errors.add(:join_limit, 'は今日以降の日時を指定してください') unless Date.today <= join_limit
  end

  def isJoined?(user)
    user_events.map(&:user_id).include?(user.id) if user
  end

  private
  def convert_to_markdown
    convert = Qiita::Markdown::Processor.new
    self.converted_description = convert.call(description)[:output].to_s
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::Base
  def index
    @event_list = Event.available_events
    @event_list = @event_list.circle_events if params[:circle] == 'true'
    @event_list = @event_list.member_events if params[:circle] == 'false'
    @event_list = @event_list.page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @participated_users = @event.participated_user.order(grade: :desc, student_number: :asc)
    @participated_users_remark = @event.user_events.map { |r| [r.user_id, r.remark] }.to_h
    respond_to do |format|
      format.html
      format.csv do
        if params[:sjis]
          participated_users_csv(Encoding::Shift_JIS)
        else
          participated_users_csv
        end
        return
      end
    end
  end

  def new
    @new_event = Event.new
  end

  def create
    @new_event = current_user.held_events.build(admin_event_params)
    @new_event.official = true
    if @new_event.save
      redirect_to admin_event_path(@new_event), success: 'イベントを登録しました'
    else
      render :new
    end
  end

  def edit
    @edit_event = Event.find(params[:id])
  end

  def update
    @edit_event = Event.find(params[:id])
    @edit_event.assign_attributes(admin_event_params)
    if @edit_event.save
      redirect_to admin_event_path(@edit_event), success: '情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @destroy_event = Event.find(params[:id])
    @destroy_event.deleted = true
    if @destroy_event.save
      redirect_to admin_events_path, success: 'イベントを削除しました'
    else
      redirect_to admin_event_path(@destroy_event), warning: 'イベントを削除出来ませんでした'
    end
  end

  private
  def admin_event_params
    params.require(:event).permit(:title, :summary, :description, :converted_description, :start_time, :join_limit, :owner_id, :official, :deleted)
  end

  def participated_users_csv(encode = Encoding::UTF_8)
    require 'csv'
    csv_date = CSV.generate(encoding: encode) do |csv|
      csv_column_names = ['学籍番号', '氏名', 'アレルギー情報', '成人', '備考']
      csv << csv_column_names
      @participated_users.each do |l|
        csv_column_values = [
          l.student_number,
          l.name,
          l.allergy_data,
          l.adult? ? '○' : '×',
          @participated_users_remark[l.id]
        ]
        csv << csv_column_values
      end
    end
    send_data(csv_date,filename: "#{@event.title}_#{I18n.l(Date.today, format: '%Y-%m-%d')}.csv")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action ->{
    require_login(user_path)
  }, except: [:index, :show, :join]

  def index
    @event_list = Event.available_events
    @event_list = @event_list.circle_events if params[:circle] == 'true'
    @event_list = @event_list.member_events if params[:circle] == 'false'
    @event_list = @event_list.page(params[:page])
  end

  def show
    @event_detail = Event.find(params[:id])
  end

  def new
    @new_event = Event.new()
  end

  def create
    @new_event = current_user.held_events.build(event_params)
    # convert = Qiita::Markdown::Processor.new
    # @new_event.converted_description = convert.call(@new_event.description)[:output].to_s
    if @new_event.save
      UserEvent.create(user: current_user, event: @new_evemt)
      redirect_to detail_user_event_path(@new_event)
    else
      render :new
    end
  end

  def edit
    @edit_event = Event.find(params[:id])
    authorize! @edit_event
  end

  def update
    @edit_event = Event.find(params[:id])
    authorize! @edit_event
    @edit_event.assign_attributes(event_params)
    if @edit_event.save
      redirect_to detail_user_event_path(@edit_event), success: '情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @destroy_event = Event.find(params[:id])
    authorize! @destroy_event
    @destroy_event.deleted = true
    if @destroy_event.save
      redirect_to held_user_events_path, success: 'イベントを削除しました'
    else
      render detail_user_event_path(@destroy_event), danger: '削除に失敗しました'
    end
  end

  def join
    begin
      raise RequireUserLogin unless current_user
      join_event = Event.find(params[:id])
      authorize! join_event
      user_event = UserEvent.new(user: current_user, event: join_event, remark: params[:remark])
      if user_event.save
        InfomationMailer.joined_email(current_user, join_event).deliver
        redirect_to joined_events_path, success: "イベントに参加しました"
      else
        redirect_to joined_events_path, warning: "すでに参加しているイベントです"
      end
    rescue Banken::NotAuthorizedError => e
      redirect_to event_path, danger: "このイベントの参加受付は終了しています"
      return
    rescue RequireUserLogin => e
      require_login(event_path(params[:id]))
    end
  end

  def unjoin
    begin
      require_login(event_path(params[:id]))
      unjoin_event = Event.find(params[:id])
      authorize! unjoin_event
    rescue Banken::NotAuthorizedError => e
      redirect_to event_path, danger: 'このイベントの参加取り消し受付は終了しています'
      return
    end
    @destroy_join = UserEvent.find_by(user: current_user, event: unjoin_event)
    if @destroy_join.destroy
      InfomationMailer.unjoined_email(current_user, unjoin_event).deliver
      redirect_to joined_events_path, success: '参加を取り消しました'
    else
      redirect_to joined_events_path, warning: '参加の取り消しに失敗しました'
    end
  end

  def joined
    @joined_list = current_user.joined_events
  end

  def held
    @held_list = current_user.held_events.available_events
  end

  def detail
    @event_detail = Event.find(params[:id])
    authorize! @event_detail
    @participated_users = @event_detail.participated_user.order(grade: :desc, student_number: :asc)
    @participated_users_remark = @event_detail.user_events.map{|r| [r.user_id,r.remark]}.to_h
    respond_to do |format|
      format.html
      format.csv do
        if params[:sjis]
          participated_users_csv(Encoding::Shift_JIS)
        else
          participated_users_csv
        end
        return
      end
    end
  end

  private
  def event_params
    params.require(:event).permit(:title, :summary, :description, :converted_description, :start_time, :join_limit, :owner_id, :deleted)
  end
  
  def participated_users_csv(encode = Encoding::UTF_8)
    require 'csv'
    csv_date = CSV.generate(encoding: encode) do |csv|
      csv_column_names = ['学籍番号', '氏名', 'アレルギー情報', '成人', '備考']
      csv << csv_column_names
      @participated_users.each do |l|
        csv_column_values = [
          l.student_number,
          l.name,
          l.allergy_data,
          l.adult? ? '○' : '×',
          @participated_users_remark[l.id]
        ]
        csv << csv_column_values
      end
    end
    send_data(csv_date, filename: "#{@event_detail.title}_#{I18n.l(Date.today, format: '%Y-%m-%d')}.csv")
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event_index.html.slim
.column.is-one-third
  .card
    header.card-header
      p.card-header-title
        = link_to list.title, admin_event_path(list)
    .card-content
      .content
        = list.summary
    footer.card-footer
      = link_to 'メール送信', admin_mailsender_create_path(target: list.id), class: 'card-footer-item'
      = link_to '編集', edit_admin_event_path(list), class: 'card-footer-item'
      = link_to '削除', admin_event_path(list), method: :delete, class: 'button is-danger card-footer-item', data: {confirm: 'このイベントを削除しますよろしいですか？'}

app/views/admin/events/_event_nav.html.slim
.tabs.is-centered
  ul
    li class="#{request.path_info == admin_events_path ? "is-active" : ''}"
      = link_to "イベント一覧", admin_events_path
    li class="#{request.path_info == new_admin_event_path ? "is-active" : ''}"
      = link_to "イベント新規登録", new_admin_event_path

app/views/admin/events/edit.html.slim
.container
  = form_with model: @edit_event, url: admin_event_path, method: :patch, local: true do |f|
    .field
      = f.label :title, class: 'label'
      = show_errors(@edit_event.errors.full_messages_for(:title))
      .control
        = f.text_field :title, class: 'input'
    .field
      = f.label :start_time, class: 'label'
      = show_errors(@edit_event.errors.full_messages_for(:start_time))
      .control
        = f.text_field :start_time, class: 'date-picker input'
    .field
      = f.label :join_limit, class: 'label'
      = show_errors(@edit_event.errors.full_messages_for(:join_limit))
      .control
        = f.text_field :join_limit, class: 'date-picker input'
    .field
      = f.label :summary, class: 'label'
      = show_errors(@edit_event.errors.full_messages_for(:summary))
      .control
        = f.text_area :summary, class: 'input'
    .field
      = f.label :description, class: 'label'
      = show_errors(@edit_event.errors.full_messages_for(:description))
      p
        | QiitaMarkdown形式で書き込んでください。書き方が分からない人は
        a href="https://qiita.com/Qiita/items/c686397e4a0f4f11683d" target="_blank" こちら
        | を参照してください
      .control
        = f.text_area :description, class: 'input'
    = f.submit "イベントを更新する", class: "button is-info"

app/views/admin/events/index.html.slim
.container
  = render partial: 'event_nav'
  .buttons.has-addons.is-centered
    = link_to '全てのイベント', admin_events_path, class: "#{!params[:circle].present? ?  'button is-info is-selected' : 'button'}"
    = link_to 'サークルイベント', admin_events_path(circle: true), class: "#{params[:circle] == 'true' ?  'button is-info is-selected' : 'button'}"
    = link_to 'メンバーイベント', admin_events_path(circle: false), class: "#{params[:circle] == 'false' ?  'button is-info is-selected' : 'button'}"
  - if @event_list.empty?
    p
      |  イベントの登録はありません。
  - else
    .columns.is-multiline
      = render partial: 'event_index', collection: @event_list, as: 'list'
    = paginate(@event_list)

app/views/admin/events/new.html.slim
.container
  = render partial: 'event_nav'
  p.notification.is-warning
    | 管理者ページでイベントを登録した場合、全て公式イベントとして登録されます。
    br
    | 公式イベントで登録したくない場合は#{link_to 'こちらから登録してください', new_user_event_path}
    button.delete
  = form_with model: @new_event, url: admin_events_path, method: :post, local: true do |f|
    .field
      = f.label :title, class: 'label'
      = show_errors(@new_event.errors.full_messages_for(:title))
      .control
        = f.text_field :title, class: 'input'
    .field
      = f.label :start_time, class: 'label'
      = show_errors(@new_event.errors.full_messages_for(:start_time))
      .control
        = f.text_field :start_time, class: 'date-picker input'
    .field
      = f.label :join_limit, class: 'label'
      = show_errors(@new_event.errors.full_messages_for(:join_limit))
      .control
        = f.text_field :join_limit, class: 'date-picker input'
    .field
      = f.label :summary, class: 'label'
      = show_errors(@new_event.errors.full_messages_for(:summary))
      .control
        = f.text_area :summary, class: 'input'
    .field
      = f.label :description, class: 'label'
      = show_errors(@new_event.errors.full_messages_for(:description))
      a#pre-input.button.is-info テンプレートを利用する(上書きされます)
      p
        | QiitaMarkdown形式で書き込んでください。書き方が分からない人は
        a href="https://qiita.com/Qiita/items/c686397e4a0f4f11683d" target="_blank" こちら
        | を参照してください
      .control
        = f.text_area :description, class: 'input'
    = f.submit "イベントを登録する", class: "button is-info"

app/views/admin/events/show.html.slim
.container
  .content
    h1= @event.title
    p 開催日: #{I18n.l(@event.start_time)}
    p 参加締め切り: #{I18n.l(@event.join_limit)}
    = @event.converted_description.html_safe
  div
    h4 参加者一覧
    - if @participated_users.present?
      .buttons
        a.button href="#{admin_event_path(params[:id], sjis: true, format: :csv)}"
          span.icon.is-small
            = fa_icon 'file-o'
          span CSVダウンロード(SJIS)
        a.button href="#{admin_event_path(params[:id], format: :csv)}"
          span.icon.is-small
            = fa_icon 'file-o'
          span CSVダウンロード(UTF-8)
      table.table.is-bordered.is-striped.is-hoverable.is-fullwidth
        tr
          th 学年
          th 学籍番号
          th 名前
          th 成人
          th アレルギー情報
          th 備考
        = render partial: 'shared/events/join_list', collection: @participated_users, locals: {remarks: @participated_users_remark} 
    - else
      p 参加者はまだいません
    .field.is-grouped
      .control
        = link_to "一覧に戻る", admin_events_path, class: 'button is-info'
      .control
        = link_to "編集", edit_admin_event_path(@event), class: 'button is-warning'
      .control
        = link_to "削除", admin_event_path(@event), method: :delete, class: 'button is-danger'