config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#index"

  get :login, :to => "session#new"
  post :login, :to => "session#create"
  post :logout, :to => "session#destroy"

  resource :user, except: [:destroy] do
    resources :events, except: [:index, :show] do
      get :held, on: :collection
      get :detail, on: :member
    end
    get :activate, on: :member
  end

  resources :events, only: [:index, :show] do
    get :join, on: :member
    post :join, on: :member
    post :unjoin, on: :member
    get :joined, on: :collection
  end

  # resources :mailsender, only: [:index] do
  #   post :check, on: :collection
  #   post :send, on: :collection
  #   get :result, on: :collection
  # end

  get '/mailsender', to: "mailsender#create", as: 'mailsender_index'
  post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
  post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'

  namespace :admin do
    root :to => "pages#index"
    resources :users
    resources :events

    get '/mailsender', to: "mailsender#index", as: 'mailsender_index'
    get '/mailsender/create', to: "mailsender#create", as: 'mailsender_create'
    post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
    post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                          :integer          not null, primary key
#  email                       :string           not null
#  crypted_password            :string
#  salt                        :string
#  name                        :string           not null
#  entrance_year               :integer          not null
#  student_number              :string           not null
#  birthday                    :date             not null
#  allergy_data                :string           default("")
#  remark                      :string           default("")
#  executive                   :boolean          default(FALSE)
#  mailer                      :boolean          default(FALSE)
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  activation_state            :string
#  activation_token            :string
#  activation_token_expires_at :datetime
#

class User < ApplicationRecord
  authenticates_with_sorcery!

  # 定数
  MAJORS = %w(CM HP HS LA LB LG LK LR LT LZ NE A E J M W)

  #列挙
  enum grade: {'pre-entry' => 0, 'freshman' => 1, 'sophomore' => 2, 'junior' => 3, 'senior' => 4, 'obog' => 5}

  # 関連
  has_many :user_events, dependent: :destroy
  has_many :held_events, class_name: 'Event', foreign_key: 'owner_id', dependent: :destroy
  has_many :joined_events, through: :user_events, source: :event

  # スコープ
  scope :grade_is, ->(g) { where(grade: g.to_i) }

  # バリデーション
  validates :password, length: { minimum: 5 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :student_number, format: {with: /\A(#{MAJORS.join('|')})\d{2}-\d{4}[A-Z]?\z/}, uniqueness: true

  # メソッド
  def age(date = Date.today)
    date_format = "%Y%m%d"
    (date.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10000
  end

  def adult?(date = Date.today)
    20 <= age(date)
  end

  def get_entrance_year
    begin
      spl = student_number.split('-')
      spl[0].gsub!(/[A-Z]{2}/,'')
      spl[1] = spl[1].slice!(0)
      if spl[1].match('1')
        y = ("20" + spl[0]).to_i
      else
        y = 1988 + spl[0].to_i
      end
      self.entrance_year = y
    rescue Exception => e
      self.entrance_year = 1989
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base
  def index
    pibot = Date.today.month <= 3 ? Date.today.year - 1 : Date.today.year
    # d = [0, -1, -2, -3, -4].map!{|r| r + pibot}

    if params[:grade].present? && 1 <= params[:grade].to_i && params[:grade].to_i <= 5
      @user_list = User.where(grade: params[:grade].to_i).page(params[:page]).order(student_number: :asc)
    else
      @user_list = User.all.page(params[:page]).order(grade: :desc, student_number: :asc)
    end
  end

  def show
    @user_detail = User.find(params[:id])
  end

  def new
    @new_user = User.new()
  end

  def create
    @new_user = User.new(user_param)
    if @new_user.save
      redirect_to :admin_root, success: "登録しました"
    else
      render :new
    end
  end

  def edit
    @edit_user = User.find(params[:id])
  end

  def update
    @edit_user = User.find(params[:id])
    @edit_user.assign_attributes(user_param)
    if @edit_user.save
      redirect_to admin_user_path(@edit_user), success: "情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @destroy_user = User.find(params[:id])
    if @destroy_user.executive? == false && @destroy_user.destroy
      redirect_to :admin_root, info: "会員情報を削除しました"
    else
      flash.now[:danger] = "幹部扱いのユーザーは削除できません"
      redirect_to admin_user_path(@destroy_user)
    end
  end

  private
  def user_param
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :student_number, :grade, :birthday, :allergy_data, :remark, :executive, :mailer)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action ->{
    require_login(user_path)
  }, except: [:new, :create, :activate]

  def show
    @user = User.find(current_user.id)
  end

  
  def new
    @new_user = User.new()
  end

  def create
    @new_user = User.new(user_param)
    if @new_user.save
      redirect_to :root, success: "アカウント認証のメールを送信しました。メールボックスをご確認ください。"
    else
      render :new
    end
  end

  def edit
    @edit_user = User.find(current_user.id)
  end

  def update
    @edit_user = User.find(current_user.id)
    @edit_user.assign_attributes(edit_user_param)
    if @edit_user.save
      redirect_to user_path, success: "情報を更新しました"
    else
      render :edit
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:token]))
      @user.activate!
      redirect_to(login_path, info: 'ユーザー認証が完了しました')
    else
      not_authenticated
    end
  end

  private
  def user_param
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :student_number, :grade, :birthday, :allergy_data, :remark)
  end

  def edit_user_param
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :allergy_data, :remark)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_nav.html.slim
.tabs.is-centered
  ul
    li class="#{request.path_info == user_path ? "is-active" : ''}"
      = link_to "ユーザーページTOP", user_path
    li class="#{request.path_info == edit_user_path ? "is-active" : ''}"
      = link_to "ユーザー情報編集", edit_user_path
    li class="#{request.path_info == joined_events_path ? "is-active" : ''}"
      = link_to "参加イベント", joined_events_path
    li class="#{request.path_info == held_user_events_path ? "is-active" : ''}"
      = link_to "開催したイベント", held_user_events_path
    li class="#{request.path_info == new_user_event_path ? "is-active" : ''}"
      = link_to "イベントを開催する", new_user_event_path

app/views/users/edit.html.slim
.container
  = render :partial => 'user_nav'
  = form_with model: @edit_user, url: user_path, method: :patch, local: true do |f|
    .field
      = f.label :email, class: 'label'
      = show_errors(@edit_user.errors.full_messages_for(:email))
      .control
        = f.email_field :email, class: 'input'
    .field
      = f.label :password, class: 'label'
      = show_errors(@edit_user.errors.full_messages_for(:password))
      .control
        = f.password_field :password, class: 'input'
    .field
      = f.label :password_confirmation, class: 'label'
      = show_errors(@edit_user.errors.full_messages_for(:password_confirmation))
      .contol
        = f.password_field :password_confirmation, class: 'input'
    .field
      = f.label :name, class: 'label'
      = show_errors(@edit_user.errors.full_messages_for(:name))
      .control
        = f.text_field :name, class: 'input'
    .field
      = f.label :student_number, class: 'label'
      .control
      = f.text_field :student_number, class: 'input', disabled: true
    .field
      = f.label :grade, class: 'label'
      .control
        span.select
          = f.select :grade, User.grades_i18n.invert, {},disabled: true
    .field
      = f.label :birthday, class: 'label'
      .control
        = f.text_field :birthday, class: 'date-picker input', disabled: true
    .field
      = f.label :allergy_data, class: 'label'
      .control
        = f.text_field :allergy_data, class: 'input'
    .field
      = f.label :remark, class: 'label'
      .contol
        = f.text_field :remark, class: 'input'
    = f.submit class: 'button is-info'

app/views/users/new.html.slim
.container
  = form_with model: @new_user, url: user_path, method: :post,  local: true do |f|
    .field
      = f.label :email, class: 'label'
      = show_errors(@new_user.errors.full_messages_for(:email))
      .control
        = f.email_field :email, class: 'input'
    .field
      = f.label :password, class: 'label'
      = show_errors(@new_user.errors.full_messages_for(:password))
      .control
        = f.password_field :password, class: 'input'
    .field
      = f.label :password_confirmation, class: 'label'
      = show_errors(@new_user.errors.full_messages_for(:password_confirmation))
      .control
        = f.password_field :password_confirmation, class: 'input'
    .field
      = f.label :name, class: 'label'
      = show_errors(@new_user.errors.full_messages_for(:name))
      = f.text_field :name, class: 'input'
    .field
      = f.label :student_number, class: 'label'
      = show_errors(@new_user.errors.full_messages_for(:student_number))
      = f.text_field :student_number, class: 'input'
    .field
      = f.label :grade, class: 'label'
      .control
        span.select
          = f.select :grade, User.grades_i18n.invert
    .field
      = f.label :birthday, class: 'label'
      .control
        = f.text_field :birthday, class: 'date-picker input'
    .field
      = f.label :allergy_data, class: 'label'
      .control
        = f.text_field :allergy_data, class: 'input'
    .field
      = f.label :remark, class: 'label'
      .control
        = f.text_field :remark, class: 'input'
    = f.submit class: 'button is-info'

app/views/users/show.html.slim
.container
  = render :partial => 'user_nav'