config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "pages#index"

  get :login, :to => "session#new"
  post :login, :to => "session#create"
  post :logout, :to => "session#destroy"

  resource :user, except: [:destroy] do
    resources :events, except: [:index, :show] do
      get :held, on: :collection
      get :detail, on: :member
    end
    get :activate, on: :member
  end

  resources :events, only: [:index, :show] do
    get :join, on: :member
    post :join, on: :member
    post :unjoin, on: :member
    get :joined, on: :collection
  end

  # resources :mailsender, only: [:index] do
  #   post :check, on: :collection
  #   post :send, on: :collection
  #   get :result, on: :collection
  # end

  get '/mailsender', to: "mailsender#create", as: 'mailsender_index'
  post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
  post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'

  namespace :admin do
    root :to => "pages#index"
    resources :users
    resources :events

    get '/mailsender', to: "mailsender#index", as: 'mailsender_index'
    get '/mailsender/create', to: "mailsender#create", as: 'mailsender_create'
    post '/mailsender/check', to: "mailsender#check", as: 'mailsender_check'
    post '/mailsender/mailsend', to: "mailsender#mailsend", as: 'mailsender_mailsend'
  end
end

app/views/shared/_alert.html.slim
- flash.each do |k,v|
  = content_tag :div, class: "notification is-#{k}", data: {'data-turbolinks' => false} do
    button.delete
    = v

app/views/shared/_navigation.html.slim
nav.navbar.is-fixed-top.is-white role="navigation" aria-label="main navigation"
  div.navbar-brand
    a.navbar-item href="#{root_path}"
      = image_tag("logo_b.svg", width: 150)
    a.navbar-burger role="button" aria-label="menu" aria-expanded="false"
      span aria-hidden="true"
      span aria-hidden="true"
      span aria-hidden="true"
  .navbar-menu
    .navbar-start
      = link_to "TOP", root_path, class: 'navbar-item'
      = link_to "イベント一覧", events_path, class: 'navbar-item'
      - if current_user
        = link_to "マイページ", user_path, class: 'navbar-item'
        = link_to "メール送信", mailsender_index_path, class: 'navbar-item'
    .navbar-end
      - if current_user
        .navbar-item
          = link_to "ログアウト", logout_path, class: 'button is-danger is-link', method: :post
        - if current_user.executive?
          = link_to "管理者TOP", admin_root_path, class: 'navbar-item'
      - else
        .navbar-item
          .field.is-grouped
            .control
              = link_to "ログイン", login_path, class: 'button is-info is-link'
            .control
              = link_to "新規登録", new_user_path, class: 'button is-success is-link'